create extension if not exists pgcrypto;
create schema if not exists private;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  offer_id text unique,
  ean text,
  title text not null,
  variant text,
  active boolean not null default true,
  current_price numeric(10,2),
  stock integer,
  fulfillment_method text,
  delivery_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  bol_order_id text unique not null,
  ordered_at timestamptz not null,
  status text,
  total_amount numeric(10,2),
  currency text not null default 'EUR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  bol_order_item_id text unique,
  product_id uuid references public.products(id) on delete set null,
  offer_id text,
  ean text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2),
  status text,
  created_at timestamptz not null default now()
);
create table if not exists public.product_metrics (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  metric_date date not null,
  visits integer,
  sales integer,
  conversion_rate numeric(8,4),
  revenue numeric(12,2),
  buy_box_percentage numeric(8,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id, metric_date)
);
create table if not exists public.competitors (
  id uuid primary key default gen_random_uuid(),
  ean text not null,
  seller_id text,
  seller_name text,
  offer_id text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);
create table if not exists public.competitor_snapshots (
  id bigint generated by default as identity primary key,
  competitor_id uuid not null references public.competitors(id) on delete cascade,
  captured_at timestamptz not null default now(),
  price numeric(10,2),
  delivery_code text,
  delivery_date date,
  seller_rating numeric,
  is_best_offer boolean,
  availability text
);
create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  records_written integer not null default 0,
  error_message text
);
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete cascade,
  alert_type text not null,
  severity text not null default 'info',
  title text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.competitor_sales_targets (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  product_url text not null unique,
  bol_product_id text,
  ean text,
  seller_name text,
  active boolean not null default true,
  tracking_mode text not null default 'cart_inference',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.competitor_stock_snapshots (
  id bigint generated by default as identity primary key,
  target_id uuid not null references public.competitor_sales_targets(id) on delete cascade,
  captured_at timestamptz not null default now(),
  available_stock integer not null check (available_stock >= 0),
  source text not null default 'cart_inference',
  note text
);

create index if not exists products_ean_idx on public.products(ean);
create index if not exists products_active_idx on public.products(active);
create index if not exists orders_ordered_at_idx on public.orders(ordered_at desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_product_id_idx on public.order_items(product_id);
create index if not exists order_items_ean_idx on public.order_items(ean);
create index if not exists product_metrics_date_idx on public.product_metrics(metric_date desc);
create index if not exists competitors_ean_idx on public.competitors(ean);
create unique index if not exists competitors_identity_uidx on public.competitors(ean, coalesce(seller_id,''), coalesce(offer_id,''));
create index if not exists competitor_snapshots_competitor_time_idx on public.competitor_snapshots(competitor_id, captured_at desc);
create index if not exists sync_runs_source_time_idx on public.sync_runs(source, started_at desc);
create index if not exists alerts_created_at_idx on public.alerts(created_at desc);
create index if not exists alerts_unread_idx on public.alerts(read_at) where read_at is null;
create index if not exists alerts_product_id_idx on public.alerts(product_id);
create index if not exists competitor_stock_snapshots_target_time_idx on public.competitor_stock_snapshots(target_id, captured_at desc);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function private.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function private.set_updated_at();
drop trigger if exists product_metrics_set_updated_at on public.product_metrics;
create trigger product_metrics_set_updated_at before update on public.product_metrics for each row execute function private.set_updated_at();
drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at before update on public.app_settings for each row execute function private.set_updated_at();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.product_metrics enable row level security;
alter table public.competitors enable row level security;
alter table public.competitor_snapshots enable row level security;
alter table public.sync_runs enable row level security;
alter table public.alerts enable row level security;
alter table public.app_settings enable row level security;
alter table public.competitor_sales_targets enable row level security;
alter table public.competitor_stock_snapshots enable row level security;

revoke all on public.products, public.orders, public.order_items, public.product_metrics, public.competitors, public.competitor_snapshots, public.sync_runs, public.alerts, public.app_settings, public.competitor_sales_targets, public.competitor_stock_snapshots from anon, authenticated;
grant all on public.products, public.orders, public.order_items, public.product_metrics, public.competitors, public.competitor_snapshots, public.sync_runs, public.alerts, public.app_settings, public.competitor_sales_targets, public.competitor_stock_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;
